CityJobcount { city: '苏州', job: '前端', jobcount: 128 }
CityJobcount { city: '西安', job: '前端', jobcount: 181 }
CityJobcount { city: '广州', job: '前端', jobcount: 1011 }
CityJobcount { city: '成都', job: '前端', jobcount: 433 }
CityJobcount { city: '深圳', job: '前端', jobcount: 1568 }
CityJobcount { city: '武汉', job: '前端', jobcount: 301 }
CityJobcount { city: '上海', job: '前端', jobcount: 2115 }
CityJobcount { city: '北京', job: '前端', jobcount: 3920 }
CityJobcount { city: '杭州', job: '前端', jobcount: 1263 }
CityJobcount { city: '南京', job: '前端', jobcount: 258 }